CREATE TABLE IF NOT EXISTS mod_opennfse_dps_audit_runs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  audit_month CHAR(7) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  total_items INT UNSIGNED NOT NULL DEFAULT 0,
  processed_items INT UNSIGNED NOT NULL DEFAULT 0,
  ok_count INT UNSIGNED NOT NULL DEFAULT 0,
  local_sem_chave_count INT UNSIGNED NOT NULL DEFAULT 0,
  sem_chave_api_count INT UNSIGNED NOT NULL DEFAULT 0,
  nao_encontrada_count INT UNSIGNED NOT NULL DEFAULT 0,
  chave_divergente_count INT UNSIGNED NOT NULL DEFAULT 0,
  erro_api_count INT UNSIGNED NOT NULL DEFAULT 0,
  sem_id_dps_count INT UNSIGNED NOT NULL DEFAULT 0,
  gap_count INT UNSIGNED NOT NULL DEFAULT 0,
  first_number INT UNSIGNED NULL,
  last_number INT UNSIGNED NULL,
  current_sequence_last_number INT UNSIGNED NULL,
  last_processed_history_id INT UNSIGNED NULL,
  description TEXT NULL,
  last_error MEDIUMTEXT NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_nfse_dps_audit_runs_month (audit_month),
  KEY idx_nfse_dps_audit_runs_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mod_opennfse_dps_audit_results (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id INT UNSIGNED NOT NULL,
  result_type VARCHAR(10) NOT NULL DEFAULT 'DPS',
  history_id INT UNSIGNED NULL,
  invoiceid INT UNSIGNED NULL,
  userid INT UNSIGNED NULL,
  event_date DATETIME NULL,
  id_dps VARCHAR(60) NULL,
  numero_dps INT UNSIGNED NULL,
  numero_nf VARCHAR(30) NULL,
  local_chave_acesso VARCHAR(60) NULL,
  api_chave_acesso VARCHAR(60) NULL,
  api_found TINYINT(1) NULL,
  audit_status VARCHAR(30) NOT NULL,
  audit_message TEXT NULL,
  api_error MEDIUMTEXT NULL,
  evidence_classification VARCHAR(30) NULL,
  evidence_count INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_nfse_dps_audit_dps (run_id, result_type, history_id),
  UNIQUE KEY uq_nfse_dps_audit_gap (run_id, result_type, numero_dps),
  KEY idx_nfse_dps_audit_run (run_id),
  KEY idx_nfse_dps_audit_status (audit_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
