<?php

declare(strict_types=1);

// Generated by tools/build-scoped-vendor.php — do not edit by hand.

require_once __DIR__ . '/composer-classloader/ClassLoader.php';

$loader = new \OpenNfseScopedClassLoader();

$psr4 = [
    'OpenNfseVendor\\GuzzleHttp\\' => [__DIR__ . '/guzzlehttp/guzzle/src'],
    'OpenNfseVendor\\GuzzleHttp\\Promise\\' => [__DIR__ . '/guzzlehttp/promises/src'],
    'GuzzleHttp\\Psr7\\' => [__DIR__ . '/guzzlehttp/psr7/src'],
    'Nfse\\' => [__DIR__ . '/nfse-nacional/nfse-php/src'],
    'OpenNfseVendor\\PhpParser\\' => [__DIR__ . '/nikic/php-parser/lib/PhpParser'],
    'NfsePdf\\' => [__DIR__ . '/paseto/nfse-nacional-pdf/src', __DIR__ . '/../src/PasetoOverrides'],
    'Psr\\Container\\' => [__DIR__ . '/psr/container/src'],
    'Psr\\EventDispatcher\\' => [__DIR__ . '/psr/event-dispatcher/src'],
    'Psr\\Http\\Client\\' => [__DIR__ . '/psr/http-client/src'],
    'Psr\\Http\\Message\\' => [__DIR__ . '/psr/http-factory/src', __DIR__ . '/psr/http-message/src'],
    'Psr\\Log\\' => [__DIR__ . '/psr/log/src'],
    'Spatie\\DataTransferObject\\' => [__DIR__ . '/spatie/data-transfer-object/src'],
    'OpenNfseVendor\\Symfony\\Contracts\\EventDispatcher\\' => [__DIR__ . '/symfony/event-dispatcher-contracts'],
    'OpenNfseVendor\\Symfony\\Polyfill\\Ctype\\' => [__DIR__ . '/symfony/polyfill-ctype'],
    'OpenNfseVendor\\Symfony\\Polyfill\\Iconv\\' => [__DIR__ . '/symfony/polyfill-iconv'],
    'OpenNfseVendor\\Symfony\\Polyfill\\Intl\\Grapheme\\' => [__DIR__ . '/symfony/polyfill-intl-grapheme'],
    'OpenNfseVendor\\Symfony\\Polyfill\\Intl\\Normalizer\\' => [__DIR__ . '/symfony/polyfill-intl-normalizer'],
    'OpenNfseVendor\\Symfony\\Polyfill\\Mbstring\\' => [__DIR__ . '/symfony/polyfill-mbstring'],
    'OpenNfseVendor\\Symfony\\Polyfill\\Php80\\' => [__DIR__ . '/symfony/polyfill-php80'],
    'OpenNfseVendor\\Symfony\\Polyfill\\Php84\\' => [__DIR__ . '/symfony/polyfill-php84'],
    'OpenNfseVendor\\Symfony\\Contracts\\Service\\' => [__DIR__ . '/symfony/service-contracts'],
    'OpenNfseVendor\\Symfony\\Component\\String\\' => [__DIR__ . '/symfony/string'],
    'OpenNfseVendor\\Symfony\\Component\\VarDumper\\' => [__DIR__ . '/symfony/var-dumper'],
    'OpenNfseVendor\\Webmozart\\Assert\\' => [__DIR__ . '/webmozart/assert/src'],
    'OpenNfse\\' => [__DIR__ . '/../src'],
];

foreach ($psr4 as $prefix => $dirs) {
    $loader->setPsr4($prefix, $dirs);
}

$classmap = [
    'Normalizer' => __DIR__ . '/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php',
    'PhpToken' => __DIR__ . '/symfony/polyfill-php80/Resources/stubs/PhpToken.php',
    'ValueError' => __DIR__ . '/symfony/polyfill-php80/Resources/stubs/ValueError.php',
    'UnhandledMatchError' => __DIR__ . '/symfony/polyfill-php80/Resources/stubs/UnhandledMatchError.php',
    'Stringable' => __DIR__ . '/symfony/polyfill-php80/Resources/stubs/Stringable.php',
    'Mysql' => __DIR__ . '/symfony/polyfill-php84/Resources/stubs/Pdo/Mysql.php',
    'Firebird' => __DIR__ . '/symfony/polyfill-php84/Resources/stubs/Pdo/Firebird.php',
    'Dblib' => __DIR__ . '/symfony/polyfill-php84/Resources/stubs/Pdo/Dblib.php',
    'Pgsql' => __DIR__ . '/symfony/polyfill-php84/Resources/stubs/Pdo/Pgsql.php',
    'Odbc' => __DIR__ . '/symfony/polyfill-php84/Resources/stubs/Pdo/Odbc.php',
    'Sqlite' => __DIR__ . '/symfony/polyfill-php84/Resources/stubs/Pdo/Sqlite.php',
    'TCPDF_COLORS' => __DIR__ . '/tecnickcom/tcpdf/include/tcpdf_colors.php',
    'TCPDF_STATIC' => __DIR__ . '/tecnickcom/tcpdf/include/tcpdf_static.php',
    'TCPDF_FONTS' => __DIR__ . '/tecnickcom/tcpdf/include/tcpdf_fonts.php',
    'QRcode' => __DIR__ . '/tecnickcom/tcpdf/include/barcodes/qrcode.php',
    'PDF417' => __DIR__ . '/tecnickcom/tcpdf/include/barcodes/pdf417.php',
    'Datamatrix' => __DIR__ . '/tecnickcom/tcpdf/include/barcodes/datamatrix.php',
    'TCPDF_IMAGES' => __DIR__ . '/tecnickcom/tcpdf/include/tcpdf_images.php',
    'TCPDF_FONT_DATA' => __DIR__ . '/tecnickcom/tcpdf/include/tcpdf_font_data.php',
    'TCPDF_FILTERS' => __DIR__ . '/tecnickcom/tcpdf/include/tcpdf_filters.php',
    'TCPDF' => __DIR__ . '/tecnickcom/tcpdf/tcpdf.php',
    'TCPDFBarcode' => __DIR__ . '/tecnickcom/tcpdf/tcpdf_barcodes_1d.php',
    'TCPDF2DBarcode' => __DIR__ . '/tecnickcom/tcpdf/tcpdf_barcodes_2d.php',
    'DateTime' => __DIR__ . '/thecodingmachine/safe/lib/DateTime.php',
    'DateTimeImmutable' => __DIR__ . '/thecodingmachine/safe/lib/DateTimeImmutable.php',
    'OpensslException' => __DIR__ . '/thecodingmachine/safe/lib/Exceptions/OpensslException.php',
    'SafeExceptionInterface' => __DIR__ . '/thecodingmachine/safe/lib/Exceptions/SafeExceptionInterface.php',
    'SimplexmlException' => __DIR__ . '/thecodingmachine/safe/lib/Exceptions/SimplexmlException.php',
    'CurlException' => __DIR__ . '/thecodingmachine/safe/lib/Exceptions/CurlException.php',
    'JsonException' => __DIR__ . '/thecodingmachine/safe/lib/Exceptions/JsonException.php',
    'PcreException' => __DIR__ . '/thecodingmachine/safe/lib/Exceptions/PcreException.php',
    'IbmDb2Exception' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/IbmDb2Exception.php',
    'PsException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/PsException.php',
    'SolrException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/SolrException.php',
    'MysqliException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/MysqliException.php',
    'ClassobjException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/ClassobjException.php',
    'LdapException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/LdapException.php',
    'FilesystemException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/FilesystemException.php',
    'Ssh2Exception' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/Ssh2Exception.php',
    'DatetimeException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/DatetimeException.php',
    'YamlException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/YamlException.php',
    'ApcuException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/ApcuException.php',
    'CalendarException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/CalendarException.php',
    'LzfException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/LzfException.php',
    'SsdeepException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/SsdeepException.php',
    'CubridException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/CubridException.php',
    'ArrayException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/ArrayException.php',
    'SessionException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/SessionException.php',
    'XmlrpcException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/XmlrpcException.php',
    'IbaseException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/IbaseException.php',
    'GmpException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/GmpException.php',
    'FpmException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/FpmException.php',
    'ComException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/ComException.php',
    'XmlException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/XmlException.php',
    'EioException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/EioException.php',
    'RpminfoException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/RpminfoException.php',
    'UrlException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/UrlException.php',
    'YazException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/YazException.php',
    'MiscException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/MiscException.php',
    'ZlibException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/ZlibException.php',
    'UodbcException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/UodbcException.php',
    'PcntlException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/PcntlException.php',
    'Oci8Exception' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/Oci8Exception.php',
    'IconvException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/IconvException.php',
    'SodiumException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/SodiumException.php',
    'PspellException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/PspellException.php',
    'SocketsException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/SocketsException.php',
    'ReadlineException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/ReadlineException.php',
    'FilterException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/FilterException.php',
    'SemException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/SemException.php',
    'DirException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/DirException.php',
    'UopzException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/UopzException.php',
    'NetworkException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/NetworkException.php',
    'StringsException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/StringsException.php',
    'SplException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/SplException.php',
    'InfoException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/InfoException.php',
    'StreamException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/StreamException.php',
    'FtpException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/FtpException.php',
    'Bzip2Exception' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/Bzip2Exception.php',
    'LibxmlException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/LibxmlException.php',
    'InotifyException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/InotifyException.php',
    'GettextException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/GettextException.php',
    'MysqlException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/MysqlException.php',
    'RnpException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/RnpException.php',
    'PgsqlException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/PgsqlException.php',
    'GnupgException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/GnupgException.php',
    'MbstringException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/MbstringException.php',
    'XdiffException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/XdiffException.php',
    'ImapException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/ImapException.php',
    'SqlsrvException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/SqlsrvException.php',
    'HashException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/HashException.php',
    'RrdException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/RrdException.php',
    'ApacheException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/ApacheException.php',
    'ImageException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/ImageException.php',
    'ShmopException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/ShmopException.php',
    'VarException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/VarException.php',
    'FunchandException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/FunchandException.php',
    'OpcacheException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/OpcacheException.php',
    'ErrorfuncException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/ErrorfuncException.php',
    'OutcontrolException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/OutcontrolException.php',
    'MailparseException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/MailparseException.php',
    'PosixException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/PosixException.php',
    'ZipException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/ZipException.php',
    'SwooleException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/SwooleException.php',
    'FileinfoException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/FileinfoException.php',
    'ExecException' => __DIR__ . '/thecodingmachine/safe/generated/Exceptions/ExecException.php',
];

$loader->addClassMap($classmap);

// Register as a fallback (append), not prepend: our Psr\* interfaces must
// never shadow the ones other WHMCS modules bundle, or their own
// (unprefixed) Guzzle/PSR-7 classes can become incompatible at runtime.
$loader->register(false);

require_once __DIR__ . '/guzzlehttp/guzzle/src/functions_include.php';
require_once __DIR__ . '/jetbrains/phpstorm-stubs/PhpStormStubsMap.php';
require_once __DIR__ . '/ralouphie/getallheaders/src/getallheaders.php';
require_once __DIR__ . '/symfony/deprecation-contracts/function.php';
require_once __DIR__ . '/symfony/polyfill-ctype/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-iconv/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-intl-grapheme/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-intl-normalizer/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-mbstring/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-php80/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-php84/bootstrap.php';
require_once __DIR__ . '/symfony/string/Resources/functions.php';
require_once __DIR__ . '/symfony/var-dumper/Resources/functions/dump.php';
require_once __DIR__ . '/thecodingmachine/safe/lib/special_cases.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/apache.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/apcu.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/array.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/bzip2.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/calendar.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/classobj.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/com.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/cubrid.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/curl.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/datetime.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/dir.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/eio.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/errorfunc.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/exec.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/fileinfo.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/filesystem.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/filter.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/fpm.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/ftp.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/funchand.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/gettext.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/gmp.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/gnupg.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/hash.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/ibase.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/ibmDb2.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/iconv.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/image.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/imap.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/info.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/inotify.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/json.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/ldap.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/libxml.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/lzf.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/mailparse.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/mbstring.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/misc.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/mysql.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/mysqli.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/network.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/oci8.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/opcache.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/openssl.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/outcontrol.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/pcntl.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/pcre.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/pgsql.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/posix.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/ps.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/pspell.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/readline.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/rnp.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/rpminfo.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/rrd.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/sem.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/session.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/shmop.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/sockets.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/sodium.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/solr.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/spl.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/sqlsrv.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/ssdeep.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/ssh2.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/stream.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/strings.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/swoole.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/uodbc.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/uopz.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/url.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/var.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/xdiff.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/xml.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/xmlrpc.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/yaml.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/yaz.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/zip.php';
require_once __DIR__ . '/thecodingmachine/safe/generated/zlib.php';

return $loader;
