<?php

namespace OpenNfseVendor;

// autoload_real.php @generated by Composer
class ComposerAutoloaderInit027535d1a7d9cca9f15703695c35a289
{
    private static $loader;
    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }
    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }
        require __DIR__ . '/platform_check.php';
        \spl_autoload_register(array('OpenNfseVendor\ComposerAutoloaderInit027535d1a7d9cca9f15703695c35a289', 'loadClassLoader'), \true, \true);
        self::$loader = $loader = new \OpenNfseVendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        \spl_autoload_unregister(array('ComposerAutoloaderInit027535d1a7d9cca9f15703695c35a289', 'loadClassLoader'));
        require __DIR__ . '/autoload_static.php';
        \call_user_func(\OpenNfseVendor\Composer\Autoload\ComposerStaticInit027535d1a7d9cca9f15703695c35a289::getInitializer($loader));
        $loader->register(\true);
        $filesToLoad = \OpenNfseVendor\Composer\Autoload\ComposerStaticInit027535d1a7d9cca9f15703695c35a289::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = \true;
                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }
        return $loader;
    }
}
